"""create phase 1 tables

Revision ID: 81399f08d329
Revises: (initial)
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "81399f08d329"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerated, then reviewed for constraint names and standalone SQL types.
    op.create_table(
        "answer",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_key", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answer")),
        sa.UniqueConstraint("question_key", name=op.f("uq_answer_question_key")),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "resume",
                "cover",
                "other",
                name=op.f("ck_document_kind_documentkind"),
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document")),
    )
    op.create_table(
        "experience",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "job",
                "project",
                "education",
                name=op.f("ck_experience_kind_experiencekind"),
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("org", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experience")),
    )
    op.create_table(
        "job",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("ats_type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    op.create_table(
        "profile",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("links", sa.JSON(), nullable=False),
        sa.Column("work_authorization", sa.String(), nullable=True),
        sa.CheckConstraint("id = 1", name=op.f("ck_profile_id_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile")),
    )
    op.create_table(
        "skill",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("proficiency", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill")),
        sa.UniqueConstraint("name", name=op.f("uq_skill_name")),
    )
    op.create_table(
        "application",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "saved",
                "preparing",
                "ready_for_review",
                "applied",
                "interviewing",
                "offer",
                "rejected",
                "withdrawn",
                name=op.f("ck_application_status_applicationstatus"),
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("resume_document_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name=op.f("fk_application_job_id_job"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resume_document_id"],
            ["document.id"],
            name=op.f("fk_application_resume_document_id_document"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application")),
        sa.UniqueConstraint("job_id", name=op.f("uq_application_job_id")),
    )
    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_application_resume_document_id"), ["resume_document_id"], unique=False
        )

    op.create_table(
        "bullet",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("experience_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("metrics", sa.String(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experience_id"],
            ["experience.id"],
            name=op.f("fk_bullet_experience_id_experience"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bullet")),
    )
    with op.batch_alter_table("bullet", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bullet_experience_id"), ["experience_id"], unique=False
        )

    op.create_table(
        "bulletskill",
        sa.Column("bullet_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bullet_id"],
            ["bullet.id"],
            name=op.f("fk_bulletskill_bullet_id_bullet"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill.id"],
            name=op.f("fk_bulletskill_skill_id_skill"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("bullet_id", "skill_id", name=op.f("pk_bulletskill")),
    )
    op.create_table(
        "statusevent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "saved",
                "preparing",
                "ready_for_review",
                "applied",
                "interviewing",
                "offer",
                "rejected",
                "withdrawn",
                name=op.f("ck_statusevent_from_status_applicationstatus"),
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "saved",
                "preparing",
                "ready_for_review",
                "applied",
                "interviewing",
                "offer",
                "rejected",
                "withdrawn",
                name=op.f("ck_statusevent_to_status_applicationstatus"),
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
            name=op.f("fk_statusevent_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statusevent")),
    )
    with op.batch_alter_table("statusevent", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_statusevent_application_id"), ["application_id"], unique=False
        )


def downgrade() -> None:
    # Autogenerated, then reviewed for constraint names and standalone SQL types.
    with op.batch_alter_table("statusevent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_statusevent_application_id"))

    op.drop_table("statusevent")
    op.drop_table("bulletskill")
    with op.batch_alter_table("bullet", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bullet_experience_id"))

    op.drop_table("bullet")
    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_application_resume_document_id"))

    op.drop_table("application")
    op.drop_table("skill")
    op.drop_table("profile")
    op.drop_table("job")
    op.drop_table("experience")
    op.drop_table("document")
    op.drop_table("answer")
