"""create phase 1 tables

Revision ID: a200917fe6d8
Revises: (initial)
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a200917fe6d8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerated, then reviewed for constraints, cascades, and portable SQL types.
    op.create_table(
        "answer",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_key", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_key"),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "resume",
                "cover",
                "other",
                name="documentkind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "experience",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "job",
                "project",
                "education",
                name="experiencekind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("org", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("ats_type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "profile",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("links", sa.JSON(), nullable=False),
        sa.Column("work_authorization", sa.String(), nullable=True),
        sa.CheckConstraint("id = 1", name="ck_profile_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skill",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("proficiency", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "application",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "saved",
                "preparing",
                "ready_for_review",
                "applied",
                "interviewing",
                "offer",
                "rejected",
                "withdrawn",
                name="applicationstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("resume_document_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resume_document_id"], ["document.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
    )
    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_application_resume_document_id"), ["resume_document_id"], unique=False
        )

    op.create_table(
        "bullet",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("experience_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("metrics", sa.String(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["experience_id"], ["experience.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bullet", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bullet_experience_id"), ["experience_id"], unique=False
        )

    op.create_table(
        "bulletskill",
        sa.Column("bullet_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["bullet_id"], ["bullet.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skill.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("bullet_id", "skill_id"),
    )
    op.create_table(
        "statusevent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "saved",
                "preparing",
                "ready_for_review",
                "applied",
                "interviewing",
                "offer",
                "rejected",
                "withdrawn",
                name="applicationstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "saved",
                "preparing",
                "ready_for_review",
                "applied",
                "interviewing",
                "offer",
                "rejected",
                "withdrawn",
                name="applicationstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["application_id"], ["application.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("statusevent", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_statusevent_application_id"), ["application_id"], unique=False
        )


def downgrade() -> None:
    # Autogenerated, then reviewed for constraints, cascades, and portable SQL types.
    with op.batch_alter_table("statusevent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_statusevent_application_id"))

    op.drop_table("statusevent")
    op.drop_table("bulletskill")
    with op.batch_alter_table("bullet", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bullet_experience_id"))

    op.drop_table("bullet")
    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_application_resume_document_id"))

    op.drop_table("application")
    op.drop_table("skill")
    op.drop_table("profile")
    op.drop_table("job")
    op.drop_table("experience")
    op.drop_table("document")
    op.drop_table("answer")
